# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats.ui'
#
# Created: Wed Oct 29 14:00:18 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Stats(object):
    def setupUi(self, Stats):
        Stats.setObjectName(_fromUtf8("Stats"))
        Stats.resize(719, 611)
        self.tabWidget = QtGui.QTabWidget(Stats)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 691, 601))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 661, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 661, 301))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(126)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 151, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(190, 50, 151, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.kplotwidget = KPlotWidget(self.tab_2)
        self.kplotwidget.setGeometry(QtCore.QRect(30, 80, 621, 211))
        self.kplotwidget.setBackgroundColor(QtGui.QColor(255, 255, 255))
        self.kplotwidget.setForegroundColor(QtGui.QColor(0, 0, 0))
        self.kplotwidget.setObjectName(_fromUtf8("kplotwidget"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(30, 50, 141, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(30, 320, 141, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.kplotwidget_2 = KPlotWidget(self.tab_2)
        self.kplotwidget_2.setGeometry(QtCore.QRect(30, 350, 621, 211))
        self.kplotwidget_2.setBackgroundColor(QtGui.QColor(255, 255, 255))
        self.kplotwidget_2.setForegroundColor(QtGui.QColor(0, 0, 0))
        self.kplotwidget_2.setProperty("grid", False)
        self.kplotwidget_2.setObjectName(_fromUtf8("kplotwidget_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 141, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(260, 10, 141, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(470, 10, 141, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.listWidget = QtGui.QListWidget(self.tab_3)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 81, 541))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.scrollArea = QtGui.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(100, 20, 571, 441))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 439))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(Stats)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Stats)

    def retranslateUi(self, Stats):
        Stats.setWindowTitle(_translate("Stats", "Stats Design", None))
        self.comboBox.setItemText(0, _translate("Stats", "Select session...", None))
        self.comboBox.setItemText(1, _translate("Stats", "Session 1", None))
        self.comboBox.setItemText(2, _translate("Stats", "Session 2", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Stats", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Stats", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Stats", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Stats", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Stats", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Stats", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Stats", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Stats", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Stats", "10", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Stats", "Guessed", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Stats", "Actual", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Stats", "Difference", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Stats", "Error", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Stats", "Image", None))
        self.label_6.setText(_translate("Stats", "Average error: 13", None))
        self.label_7.setText(_translate("Stats", "Margin: +123", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Stats", "Sessions", None))
        self.label.setText(_translate("Stats", "Average Error: 123", None))
        self.label_2.setText(_translate("Stats", "Average Margin: 123", None))
        self.label_3.setText(_translate("Stats", "Total guesses: 123", None))
        self.label_4.setText(_translate("Stats", "Total something: 123", None))
        self.label_5.setText(_translate("Stats", "Total stuff: 123", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Stats", "Lifetime", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Stats", "session 1", None))
        item = self.listWidget.item(1)
        item.setText(_translate("Stats", "session 2", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Stats", "Image-focused tabs?", None))

from PyKDE4.kdeui import KPlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Stats = QtGui.QWidget()
    ui = Ui_Stats()
    ui.setupUi(Stats)
    Stats.show()
    sys.exit(app.exec_())

